# This is a basic workflow to help you get started with Actions

name: build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update_Submodule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: auto update submodule
        run: |
         git submodule update --remote --merge 
         git add .
         git commit -m "update submodule"
         git push origin main   
           
  build_Linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: run shell script
        run: |
         sudo apt install -y libx11-dev libxft-dev libxext-dev base mesa-utils
         bash ./build.sh

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  #build_MacOs:
  build_Window:
      runs-on: window
      steps: 
       - uses: actions/checkout@v2
       - name: run batch scripts
         run: build.bat
                              
